service: videothumb
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  videoprobe:
    handler: videoprobe.handler_http_get
    package:
      include:
        - videoprobe.py
        - lib.py
        - bin/ffprobe
    events:
      - http:
          path: /videoprobe
          method: get


#    Define function environment variables here
#    environment:
#      variable2: value2

