service: videothumb
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  videoprobe:
    handler: videoprobe.handler_http_get
    package:
      include:
        - videoprobe.py
        - bin/ffprobe
        - lib.py
    events:
      - http:
          path: /videoprobe
          method: get
  videoprobe:
    handler: videothumb.handler_http_get
    package:
      include:
        - videothumb.py
        - bin/ffmpeg
        - lib.py
        - certifi
        - chardet
        - idna
        - requests
        - urllib3
    events:
      - http:
          path: /videothumb
          # should be POST? since we're creating a new S3 object?
          method: get
